image: python:latest

pages:
  stage: deploy
  only:
    - master
  script:
    - pip install mkdocs-material
    - pip install Pygments
    - pip install pymdown-extensions 
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  